name: biol5472_groupB
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - jinja2=3.*
  - pandas=2.*
  - pip
  - snakemake=9.*
  - numpy=1.*
  - matplotlib=3.*
  - seaborn=0.*
  - biopython=1.*
  - pip:
      - gffutils>=0.12

